---

- name: "create backend app directory"
  file:
    path: /home/ubuntu/backend
    state: directory

- name: " unarchive backend"
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend

- name: "install npm"
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm i

# - name: "create systemd service for app"
#   become: true
#   copy:
#     src: nodejs_backend.service
#     dest: /etc/systemd/system/nodejs_backend.service

# - name: "reload systemd daemon"
#   become: true
#   systemd:
#     daemon_reload: yes

# - name: "enable and start app service"
#   become: true
#   service:
#     name: nodejs_backend
#     enabled: yes
#     state: started

- name: start app 
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm install
    pm2 stop default
    pm2 start npm -- start
    cd dist
    pm2 start main.js --update-env