---
- name: "create backend app directory"
  file:
    path: /home/ubuntu/backend
    state: directory
- name: " unarchive backend"
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend

- name: "install npm"
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm i
  

- name: " run node app using pm2"
  shell: |
    cd /home/ubuntu/backend/dist
    pm2 stop default
    pm2 start -f main.js
  register: execute_node

- name: " print message"
  debug:
    msg: "{{execute_node.stdout_lines}}"

- name: " configure pm2 to start as service"
  shell: |
     sudo su -c "env PATH=$PATH:/usr/local/bin  pm2 startup systemd -u ubuntu --hp /home/ubuntu"
     pm2 save
